name: Update WakaTime Stats
# To run this workflow, create and push a git tag:
# git tag <tagname>
# git push origin <tagname>
on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Keep this so you can also run it manually from the UI
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          LANG_COUNT: 30
